service: users-authoriser
app: bizzflow
frameworkVersion: "2"
description: BizzFlow Lambda authorizer

custom:
  application: BizzFlow

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: eu-central-1

  environment:
    NODE_ENV: dev
    SYSTEM: ${self:service}-${opt:stage, self:provider.stage}
    USERS_TABLE: users-${opt:stage, self:provider.stage}

plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  authorizer:
    handler: src/handler.jwtAuth
    tags:
          application: ${self:custom.application}
          service: ${self:service}


resources:
  Resources:
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ApiGateway

  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGateway
      Export:
        Name: api-gateway:${opt:stage, self:provider.stage}:rest-api-id
    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGateway
          - RootResourceId
      Export:
        Name: api-gateway:${opt:stage, self:provider.stage}:root-resource-id

    Authorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: Authorizer
        Type: REQUEST
        AuthorizerUri:
          Fn::Join: [ "",
            [
              "arn:aws:apigateway:",
              "${self:custom.region}",
              ":lambda:path/",
              "2015-03-31/functions/",
              Fn::GetAtt: ["AuthorizerLambdaFunction", "Arn" ],
              "/invocations"
            ]]
        RestApiId:
          Fn::ImportValue: api-gateway:${opt:stage, self:provider.stage}:rest-api-id
    apiGatewayLambdaPermissions:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt: [ AuthorizerLambdaFunction, Arn]
        Action: lambda:InvokeFunction
        Principal:
          Fn::Join: [ "",
            [
              "apigateway.",
              Ref: AWS::URLSuffix
            ]]
