service: users-authoriser
app: bizzflow
frameworkVersion: "2"
description: BizzFlow Lambda authorizer

custom:
  application: BizzFlow

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stackName: ${self:service}-${opt:stage, self:provider.stage}-stack 
  apiName: ${self:service}-${opt:stage, self:provider.stage}-api 

  stage: dev
  region: eu-central-1

  environment:
    NODE_ENV: dev
    SYSTEM: ${self:service}-${opt:stage, self:provider.stage}
    USERS_TABLE: users-${opt:stage, self:provider.stage}
    API_GATEWAY: ${self:custom.application}-ApiGW

plugins:
  - serverless-plugin-typescript 
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  basicUserAuthorizer:
    handler: src/handler.jwtAuth
    tags:
          application: ${self:custom.application}
          service: ${self:service}

resources:
  Resources:
    BizzFlowApiGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: BizzFlowApiGW

  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: BizzFlowApiGW
      Export:
        Name: BizzFlowApiGateway-restApiId-${opt:stage, self:provider.stage}
