service: users-authoriser
app: bizzflow
frameworkVersion: "2"
description: BizzFlow Lambda authorizer

custom:
  application: BizzFlow

provider:
  name: aws
  runtime: nodejs14.x

  stage: dev
  region: eu-central-1

  environment:
    NODE_ENV: dev
    SYSTEM: ${self:service}-${opt:stage, self:provider.stage}
    USERS_TABLE: users-${opt:stage, self:provider.stage}

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  jwtAuth:
    handler: src/handler.jwtAuth
